### ISSUE TITLE
The meaning of some arguments

### ISSUE THREAD

**Issue by jinyu121** [srebuffi/iCaRL#2]
Hi~

Could you please explain the meaning of "[group](https://github.com/srebuffi/iCaRL/blob/78669fdf0463227309ee68c4ca455efd61e86645/iCaRL-Tensorflow/main_resnet_tf.py#L21)"? I can not understand what the "group" for, and can not find the notation in the paper.

By my guess, you mean "if we have 24 classes in total, and I want to run 3 times, so the class numbers in each iteration are 1-8, 9-16 and 17-24".

And

Is [there](https://github.com/srebuffi/iCaRL/blob/78669fdf0463227309ee68c4ca455efd61e86645/iCaRL-Tensorflow/main_resnet_tf.py#L54) the hard-coded image net 1000 class? If I have a dataset contains 24 class, can I change 1000 to 24 here?
 
THX

**Comment by srebuffi** [comment]
Hi,
in this context of incremental learning, a "group" in my code designates the incoming batch of classes (or dataset) you want to add to the current representation. So to add 24 classes in 3 times, you use "nb_cl = 8" (8 classes at a time) and "nb_groups = 3" (for the separation of the classes in 3 groups).

For the second question, you can change 1000 to 24 but you also have to change [here](https://github.com/srebuffi/iCaRL/blob/78669fdf0463227309ee68c4ca455efd61e86645/iCaRL-Tensorflow/main_resnet_tf.py#L63) to load your dataset instead of ImageNet. To load your dataset after having learned ImageNet would require some modification of the code but nothing big (initialize the network with pretrained ImageNet instead of random weights).

I hope this helped.
Best wishes,

Sylvestre
